//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int RoomId { get; set; }
        public string Message { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
